version: '3.3'

services:
  application:
    container_name: proxy-core-api
    hostname: proxy-core-api
    build:
      context: ./
      dockerfile: ./core/Dockerfile
    environment:
      FLASK_DEBUG: 1
      PYTHONBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    restart: always
    volumes:
      - ./src/application:/app
    ports:
      - 5555:5000
    command: sh -c "./run_api.sh"